stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: node:18-alpine4.0
  script:
    - npm install
    - npm build

test-job:
  stage: test
  image: node:18-alpine4.0
  script:
    - npm install
    - npm test

deploy-dev:
  stage: deploy
  image: node:18-alpine4.0
  script:
    - echo "Running deploy step"
