version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/build
          paths:
            - .

  deploy:
    docker:
        - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: ~/build
      - aws-s3/sync:
          from: build
          to: 's3://todo-kv-develop'

workflows:
  deploy_to_dev:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: dev

